brew "bitcoin"
brew "cloudflared"
brew "fish"
brew "helix"

cask "iina"
cask "ghostty"
cask "mullvad-browser"
cask "mullvad-vpn"
cask "oversight"
cask "raycast"
cask "tailscale-app"
cask "ungoogled-chromium"
cask "zed"
